# Generated by Django 3.2.16 on 2023-01-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('content_type', 'object_id', 'tcid')},
        ),
    ]
