# Generated by Django 3.2.16 on 2023-01-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='tstid',
            new_name='tsid',
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('task', 'tsid')},
        ),
    ]
