# Generated by Django 3.2.16 on 2023-01-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230102_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedfile',
            old_name='ofid',
            new_name='tfid',
        ),
    ]
