# Generated by Django 3.2.16 on 2023-01-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0003_rename_ofid_attachedfile_tfid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'ptid')},
        ),
    ]
