# Generated by Django 3.2.16 on 2023-01-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0004_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachedfile',
            unique_together={('content_type', 'object_id', 'tfid')},
        ),
    ]
