# Generated by Django 3.2.16 on 2023-01-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_attachedfile_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachedfile',
            options={'ordering': ['tfid']},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['tsid']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['ptid']},
        ),
    ]
